# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ca7e54880b1fb484d0d2b77b4a6a51b22ad981e260a1e173756b7de70cdc728f5982cb2d7c6e667994cbeec26bd33b092e3683878c7c04312b2431d5f2ef82e

test:
  secret_key_base: ca73a3454f3ada857eef6fe74310b1d6781f41cbe0a821ad482914ebda50a5a56c36bba6c5a8b9e71b0a804bc65ae3e9c3efd667c09a4d6219aaf11b518d15c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
